webtalk_init -webtalk_dir C:/Users/BaSO4/Desktop/study/2023-2024/Vivado/Data_selector8/Data_selector8.sim/sim_1/behav/xsim/xsim.dir/Data_selector8_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 25 21:15:37 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0eba4c2b-9748-4e80-b23e-35a00b6f3e4c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1d79c38165e64fd98865eb89712a73f1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 5800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8864_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1487989739 -regid "" -xml C:/Users/BaSO4/Desktop/study/2023-2024/Vivado/Data_selector8/Data_selector8.sim/sim_1/behav/xsim/xsim.dir/Data_selector8_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/BaSO4/Desktop/study/2023-2024/Vivado/Data_selector8/Data_selector8.sim/sim_1/behav/xsim/xsim.dir/Data_selector8_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/BaSO4/Desktop/study/2023-2024/Vivado/Data_selector8/Data_selector8.sim/sim_1/behav/xsim/xsim.dir/Data_selector8_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
